---
## What kind of widget your widget is (compile_html or compile_flash)
type: compile_html

# The location of your engine 
target: creator.html

# What assets to include with your engine
include:
  - font
  - css
  - js
